import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    alignSelf: 'stretch',
    height: 20,
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 0,
  },
  track: {
    backgroundColor: '#333',
    height: 2,
    position: 'relative',
    top: 10,
    width: '100%',
    borderRadius: 1,
  },
  fill: {
    backgroundColor: '#FFF',
    height: 2,
    width: '100%',
    borderRadius: 1,
  },
  handle: {
    position: 'absolute',
    marginLeft: -12,
    height: 24,
    width: 24,
  },
  circle: {
    borderRadius: 4,
    position: 'relative',
    top: 7,
    left: 8,
    height: 8,
    width: 8,
  },
  snapMarker: {
    position: 'absolute',
    top: 5,
    width: 2,
    height: 12,
    borderRadius: 1,
    backgroundColor: 'rgba(255,255,255,0.72)',
  },
  preview: {
    position: 'absolute',
    bottom: 30,
    width: 160,
    height: 90,
    overflow: 'hidden',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    backgroundColor: 'rgba(12,12,12,0.96)',
    zIndex: 20,
    elevation: 20,
  },
  previewImage: {
    width: '100%',
    height: '100%',
  },
  previewPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(28,28,28,0.96)',
  },
  previewLoading: {
    ...StyleSheet.absoluteFill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  previewTimestampContainer: {
    position: 'absolute',
    right: 5,
    bottom: 5,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: 'rgba(0,0,0,0.72)',
  },
  previewTimestamp: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '500',
  },
});
